package com.dazzle.asklepios.web.rest.vm.appointment;
import com.dazzle.asklepios.domain.enumeration.AppointmentStatus;
import com.dazzle.asklepios.domain.enumeration.BookingMode;
import com.dazzle.asklepios.domain.enumeration.EncounterPriority;
import com.dazzle.asklepios.domain.enumeration.EncounterReason;
import com.dazzle.asklepios.domain.enumeration.TemplateType;
import java.time.Instant;

public record AppointmentLogResponseVM(
        Long id,
        Long appointmentId,
        String operationType,
        Instant logDate,
        String logBy,
        Long facilityId,
        String facilityName,
        Long departmentId,
        String departmentName,
        Long availabilityGenerationBatchId,
        TemplateType resourceType,
        Long resourceId,
        String resourceName,
        Integer capacityIndex,
        Instant startDatetime,
        Instant endDatetime,
        Long patientId,
        String patientName,
        Long defaultServiceId,
        String defaultServiceName,
        Long defaultPractitionerId,
        String defaultPractitionerName,
        String reason,
        BookingMode bookingMode,
        AppointmentStatus status,
        EncounterReason service,
        Long serviceGroupId,
        Boolean deferred,
        Instant deferredAt,
        Boolean requireConfirmation,
        String noShowReason,
        String cancelReason,
        String cancelledBy,
        EncounterPriority priority,
        String originType,
        String originName,
        String note,
        Long followUpEncounterId,
        Long bookingGroupId,
        Long waitingListId,
        String hl7AppointmentNumber
) {
}
