package com.dazzle.asklepios.service;

import com.dazzle.asklepios.client.notification.dto.NotificationResolvedRecipientDTO;
import com.dazzle.asklepios.client.setup.dto.DepartmentDTO;
import com.dazzle.asklepios.domain.DiagnosticOrder;
import com.dazzle.asklepios.domain.DiagnosticOrderTest;
import com.dazzle.asklepios.domain.Patient;
import com.dazzle.asklepios.domain.PatientEncounter;
import com.dazzle.asklepios.domain.enumeration.DiagnosticOrderTestStatus;
import com.dazzle.asklepios.domain.enumeration.DiagnosticStatus;
import com.dazzle.asklepios.domain.enumeration.TestType;
import com.dazzle.asklepios.domain.enumeration.notification.NotificationCode;
import com.dazzle.asklepios.repository.DiagnosticOrderRepository;
import com.dazzle.asklepios.repository.DiagnosticOrderTestRepository;
import com.dazzle.asklepios.repository.PatientEncounterRepository;
import com.dazzle.asklepios.repository.PatientRepository;
import com.dazzle.asklepios.security.SecurityUtils;
import com.dazzle.asklepios.service.dto.medicalsheets.diagnosticorders.DiagnosticOrderCreateDTO;
import com.dazzle.asklepios.service.dto.medicalsheets.diagnosticorders.DiagnosticOrderUpdateDTO;
import com.dazzle.asklepios.service.helper.DepartmentHelper;
import com.dazzle.asklepios.service.helper.FacilityHelper;
import com.dazzle.asklepios.service.helper.NotificationHelper;
import com.dazzle.asklepios.web.rest.errors.BadRequestAlertException;
import com.dazzle.asklepios.web.rest.errors.NotFoundAlertException;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import jakarta.persistence.criteria.Subquery;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@Transactional
@RequiredArgsConstructor
public class DiagnosticOrderService {

    private static final Logger LOG = LoggerFactory.getLogger(DiagnosticOrderService.class);

    private final DiagnosticOrderRepository diagnosticOrderRepository;
    private final DiagnosticOrderTestRepository diagnosticOrderTestRepository;
    private final PatientRepository patientRepository;
    private final PatientEncounterRepository patientEncounterRepository;
    private final FacilityHelper facilityHelper;
    private final DepartmentHelper departmentHelper;
    private final NotificationHelper notificationHelper;


    /**
     * Creates a new {@link DiagnosticOrder}.
     * <p>
     * Defaults applied when fields are not provided:
     * - status defaults to {@link DiagnosticStatus#NEW}
     * - labStatus defaults to {@link DiagnosticStatus#NEW}
     * - radStatus defaults to {@link DiagnosticStatus#NEW}
     * - isUrgent defaults to {@code false}
     * <p>
     * Notes:
     * - saveDraft is expected to be controlled by the caller (UI/controller).
     * - orderNumber is generated by the database (not set here).
     */
    public DiagnosticOrder create(DiagnosticOrderCreateDTO dto) {
        LOG.debug("[DiagnosticOrderService] CREATE payload={}", dto);
        LOG.info("[DiagnosticOrderService] CREATE requested. patientId={} encounterId={} fromFacilityId={} fromDepartmentId={} isUrgent={}",
                dto.patientId(), dto.encounterId(), dto.fromFacilityId(), dto.fromDepartmentId(), dto.isUrgent());
        Patient patient = patientRepository.findById(dto.patientId())
                .orElseThrow(() -> {
                    LOG.warn("[DiagnosticOrderService] CREATE rejected. reason=patient_not_found patientId={}", dto.patientId());
                    return new NotFoundAlertException(
                            "Patient not found with id " + dto.patientId(),
                            "patient",
                            "notfound"
                    );
                });
        PatientEncounter encounter = patientEncounterRepository.findById(dto.encounterId())
                .orElseThrow(() -> {
                    LOG.warn("[DiagnosticOrderService] CREATE rejected. reason=encounter_not_found encounterId={}", dto.encounterId());
                    return new NotFoundAlertException(
                            "PatientEncounter not found with id " + dto.encounterId(),
                            "patientEncounter",
                            "notfound"
                    );
                });

        facilityHelper.validateFacilityExists(dto.fromFacilityId());
        departmentHelper.validateDepartmentExists(dto.fromDepartmentId());
        DiagnosticOrder order = new DiagnosticOrder();

        order.setEncounterId(encounter.getId());
        order.setPatientId(patient.getId());
        order.setFromDepartmentId(dto.fromDepartmentId());
        order.setFromFacilityId(dto.fromFacilityId());

        DiagnosticStatus labStatus = dto.labStatus() != null ? dto.labStatus() : DiagnosticStatus.NEW;
        DiagnosticStatus radStatus = dto.radStatus() != null ? dto.radStatus() : DiagnosticStatus.NEW;

        order.setStatus(DiagnosticStatus.NEW);
        order.setLabStatus(labStatus);
        order.setRadStatus(radStatus);


        order.setSaveDraft(true);
        order.setIsUrgent(dto.isUrgent() != null ? dto.isUrgent() : false);

        DiagnosticOrder saved = diagnosticOrderRepository.save(order);

        LOG.info(
                "[DiagnosticOrderService] CREATE completed. orderId={} status={} saveDraft={} labStatus={} radStatus={} isUrgent={} fromDepartmentId={} fromFacilityId={}",
                saved.getId(), saved.getStatus(), saved.getSaveDraft(),
                saved.getLabStatus(), saved.getRadStatus(), saved.getIsUrgent(),
                saved.getFromDepartmentId(), saved.getFromFacilityId()
        );

        return saved;
    }


    public DiagnosticOrder update(DiagnosticOrder existing, DiagnosticOrderUpdateDTO dto) {
        LOG.debug("[DiagnosticOrderService] UPDATE payload. orderId={} payload={}", existing.getId(), dto);
        LOG.info("[DiagnosticOrderService] UPDATE requested. orderId={} currentIsUrgent={} requestedIsUrgent={}",
                existing.getId(), existing.getIsUrgent(), dto.isUrgent());

        Boolean oldIsUrgent = existing.getIsUrgent();

        if (dto.isUrgent() != null) {
            existing.setIsUrgent(dto.isUrgent());
        }

        DiagnosticOrder saved = diagnosticOrderRepository.save(existing);

        LOG.info(
                "[DiagnosticOrderService] UPDATE completed. orderId={} status={} saveDraft={} oldIsUrgent={} newIsUrgent={}",
                saved.getId(), saved.getStatus(), saved.getSaveDraft(), oldIsUrgent, saved.getIsUrgent()
        );

        return saved;
    }

    /**
     * Retrieves diagnostic orders by encounter id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByEncounter(Long encounterId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER - encounterId={} pageable={}", encounterId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByEncounterId(encounterId, pageable);

        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER - done. encounterId={} returned={} totalElements={} totalPages={}",
                encounterId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    public Page<DiagnosticOrder> findByEncounterAndStatus(Long encounterId, DiagnosticStatus status, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER_AND_STATUS - encounterId={} status={} pageable={}",
                encounterId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByEncounterIdAndStatus(encounterId, status, pageable);

        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER_AND_STATUS - done. encounterId={} status={} returned={} totalElements={} totalPages={}",
                encounterId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    /**
     * Retrieves diagnostic orders by patient id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByPatient(Long patientId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT - patientId={} pageable={}", patientId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_Id(patientId, pageable);

        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT - done. patientId={} returned={} totalElements={} totalPages={}",
                patientId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    public Page<DiagnosticOrder> findByPatientAndStatus(Long patientId, DiagnosticStatus status, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_STATUS - patientId={} status={} pageable={}",
                patientId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndStatus(patientId, status, pageable);

        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_STATUS - done. patientId={} status={} returned={} totalElements={} totalPages={}",
                patientId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    /**
     * Retrieves diagnostic orders by patient id + encounter id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByPatientAndEncounter(Long patientId, Long encounterId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER - patientId={} encounterId={} pageable={}",
                patientId, encounterId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndEncounterId(patientId, encounterId, pageable);

        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER - done. patientId={} encounterId={} returned={} totalElements={} totalPages={}",
                patientId, encounterId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    public Page<DiagnosticOrder> findByPatientAndEncounterAndStatus(
            Long patientId,
            Long encounterId,
            DiagnosticStatus status,
            Pageable pageable
    ) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER_AND_STATUS - patientId={} encounterId={} status={} pageable={}",
                patientId, encounterId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndEncounterIdAndStatus(
                patientId, encounterId, status, pageable
        );

        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER_AND_STATUS - done. patientId={} encounterId={} status={} returned={} totalElements={} totalPages={}",
                patientId, encounterId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());

        return page;
    }

    /**
     * Submits a draft order.
     * <p>
     * Side effects:
     * - Updates order: saveDraft=false, status=SUBMITTED, submittedBy/submittedDate set
     * - Updates tests: bulk updates all tests under this order to SUBMITTED, excluding CANCELLED tests
     */
    @Transactional
    public DiagnosticOrder submit(DiagnosticOrder existing, String submittedBy) {
        LOG.info("[DiagnosticOrderService] SUBMIT requested. orderId={} currentSaveDraft={} currentStatus={} submittedBy={}",
                existing.getId(), existing.getSaveDraft(), existing.getStatus(), submittedBy);

        DiagnosticStatus oldStatus = existing.getStatus();

        existing.setSaveDraft(false);
        existing.setStatus(DiagnosticStatus.SUBMITTED);
        existing.setSubmittedBy(submittedBy);
        existing.setSubmittedDate(Instant.now());

        DiagnosticOrder saved = diagnosticOrderRepository.save(existing);

        int updatedTests = diagnosticOrderTestRepository.bulkUpdateStatusForOrder(
                saved.getId(),
                DiagnosticOrderTestStatus.SUBMITTED
        );

        LOG.info("[DiagnosticOrderService] Status changed. orderId={} oldStatus={} newStatus={} submittedBy={}",
                saved.getId(), oldStatus, saved.getStatus(), submittedBy);
        LOG.info("[DiagnosticOrderService] SUBMIT completed. orderId={} newSaveDraft={} submittedDate={} updatedTests={}",
                saved.getId(), saved.getSaveDraft(), saved.getSubmittedDate(), updatedTests);

        notificationForUrgentDiagnosticOrder(saved);

        return saved;
    }

    @Transactional
    public DiagnosticOrder submit(Long orderId, String submittedBy) {
        DiagnosticOrder order = findById(orderId);
        if (Boolean.FALSE.equals(order.getSaveDraft())) {
            LOG.warn("[DiagnosticOrderService] SUBMIT rejected. orderId={} reason=already_submitted currentStatus={} saveDraft={}",
                    orderId, order.getStatus(), order.getSaveDraft());
            throw new BadRequestAlertException(
                    "already_submitted",
                    "diagnostic_orders",
                    "Order already submitted"
            );
        }
        return submit(order, submittedBy);
    }

    /**
     * Deletes a diagnostic order by id.
     * <p>
     * Note:
     * - This does not cascade delete tests unless configured at DB/entity level.
     * - Controller is responsible for guarding deletion business rules if any.
     */
    public void delete(Long id) {
        LOG.info("[DiagnosticOrderService] DELETE requested. orderId={}", id);
        diagnosticOrderRepository.deleteById(id);
        LOG.info("[DiagnosticOrderService] DELETE completed. orderId={}", id);
    }

    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> filter(
            Long patientId,
            List<Long> patientIdIn,
            Long encounterId,
            DiagnosticStatus status,
            List<DiagnosticStatus> statusIn,
            List<DiagnosticStatus> statusNotIn,
            DiagnosticStatus excludeStatus,
            Boolean saveDraft,
            Boolean isUrgent,
            String labStatus,
            List<String> labStatusIn,
            String radStatus,
            Instant submittedDateFrom,
            Instant submittedDateTo,
            Long departmentId,
            List<Long> fromDepartmentIdIn,
            TestType testType,
            String orderNumber,
            Pageable pageable
    ) {
        LOG.debug("[DiagnosticOrderService] FILTER criteria. patientId={} patientIdIn={} encounterId={} status={} statusIn={} statusNotIn={} excludeStatus={} saveDraft={} isUrgent={} labStatus={} labStatusIn={} radStatus={} submittedDateFrom={} submittedDateTo={} departmentId={} fromDepartmentIdIn={} testType={} orderNumber={} pageable={}",
                patientId, patientIdIn, encounterId, status, statusIn, statusNotIn, excludeStatus, saveDraft, isUrgent,
                labStatus, labStatusIn, radStatus, submittedDateFrom, submittedDateTo, departmentId, fromDepartmentIdIn, testType, orderNumber, pageable);

        if (status != null && statusIn != null && !statusIn.isEmpty()) {
            LOG.warn("[DiagnosticOrderService] FILTER rejected. reason=conflicting_status_filters status={} statusIn={}", status, statusIn);
            throw new BadRequestAlertException(
                    "invalid_filter",
                    "diagnostic_orders",
                    "Use either status or statusIn, not both"
            );
        }

        Specification<DiagnosticOrder> filterSpec = (orderRoot, criteriaQuery, criteriaBuilder) -> {
            List<Predicate> filterPredicates = new ArrayList<>();

            if (patientId != null) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("patientId"), patientId));
            }

            if (patientIdIn != null && !patientIdIn.isEmpty()) {
                filterPredicates.add(orderRoot.get("patientId").in(patientIdIn));
            }

            if (encounterId != null) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("encounterId"), encounterId));
            }

            if (status != null) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("status"), status));
            }

            if (statusIn != null && !statusIn.isEmpty()) {
                filterPredicates.add(orderRoot.get("status").in(statusIn));
            }

            if (excludeStatus != null) {
                filterPredicates.add(criteriaBuilder.notEqual(orderRoot.get("status"), excludeStatus));
            }

            if (statusNotIn != null && !statusNotIn.isEmpty()) {
                filterPredicates.add(criteriaBuilder.not(orderRoot.get("status").in(statusNotIn)));
            }

            if (saveDraft != null) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("saveDraft"), saveDraft));
            }

            if (isUrgent != null) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("isUrgent"), isUrgent));
            }

            if (labStatus != null && !labStatus.isBlank()) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("labStatus"), labStatus));
            }

            if (labStatusIn != null && !labStatusIn.isEmpty()) {
                filterPredicates.add(
                        orderRoot.get("labStatus").in(labStatusIn)
                );
            }

            if (radStatus != null && !radStatus.isBlank()) {
                filterPredicates.add(criteriaBuilder.equal(orderRoot.get("radStatus"), radStatus));
            }

            if (submittedDateFrom != null) {
                filterPredicates.add(criteriaBuilder.greaterThanOrEqualTo(
                        orderRoot.get("submittedDate"),
                        submittedDateFrom
                ));
            }

            if (submittedDateTo != null) {
                filterPredicates.add(criteriaBuilder.lessThanOrEqualTo(
                        orderRoot.get("submittedDate"),
                        submittedDateTo
                ));
            }

            if (fromDepartmentIdIn != null && !fromDepartmentIdIn.isEmpty()) {
                filterPredicates.add(orderRoot.get("fromDepartmentId").in(fromDepartmentIdIn));
            }

            if (orderNumber != null && !orderNumber.isBlank()) {
                filterPredicates.add(
                        criteriaBuilder.like(
                                criteriaBuilder.lower(orderRoot.get("orderNumber")),
                                "%" + orderNumber.trim().toLowerCase() + "%"
                        )
                );
            }

            if (departmentId != null) {
                Subquery<Long> orderTestSubquery = criteriaQuery.subquery(Long.class);
                Root<DiagnosticOrderTest> orderTestRoot = orderTestSubquery.from(DiagnosticOrderTest.class);

                List<Predicate> subqueryPredicates = new ArrayList<>();

                subqueryPredicates.add(criteriaBuilder.equal(
                        orderTestRoot.get("orderId"),
                        orderRoot.get("id")
                ));

                subqueryPredicates.add(criteriaBuilder.equal(
                        orderTestRoot.get("receivedDepartmentId"),
                        departmentId
                ));

                subqueryPredicates.add(criteriaBuilder.notEqual(
                        orderTestRoot.get("status"),
                        DiagnosticOrderTestStatus.CANCELLED
                ));

                if (testType != null) {
                    subqueryPredicates.add(criteriaBuilder.equal(
                            orderTestRoot.get("orderType"),
                            testType
                    ));
                }

                orderTestSubquery.select(orderTestRoot.get("id"))
                        .where(subqueryPredicates.toArray(new Predicate[0]));

                filterPredicates.add(criteriaBuilder.exists(orderTestSubquery));
            }

            return criteriaBuilder.and(filterPredicates.toArray(new Predicate[0]));
        };

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findAll(filterSpec, pageable);
        LOG.debug("[DiagnosticOrderService] FILTER result. returned={} totalElements={} totalPages={}",
                page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages());
        return page;
    }

    @Transactional(readOnly = true)
    public DiagnosticOrder findById(Long orderId) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_ID request. orderId={}", orderId);

        DiagnosticOrder order = diagnosticOrderRepository.findById(orderId)
                .orElseThrow(() -> {
                    LOG.warn("[DiagnosticOrderService] FIND_BY_ID rejected. reason=order_not_found orderId={}", orderId);
                    return new BadRequestAlertException(
                            "notfound",
                            "diagnostic_orders",
                            "DiagnosticOrder not found with id " + orderId
                    );
                });

        LOG.debug("[DiagnosticOrderService] FIND_BY_ID result. orderId={} status={} saveDraft={}",
                order.getId(), order.getStatus(), order.getSaveDraft());

        return order;
    }

    public Set<Long> findEncounterIdsWithOrders(List<Long> encounterIds) {
        if (encounterIds == null || encounterIds.isEmpty()) {
            return Collections.emptySet();
        }

        return diagnosticOrderRepository.findDistinctByEncounterIdIn(encounterIds)
                .stream()
                .map(DiagnosticOrder::getEncounterId)
                .collect(Collectors.toSet());
    }

    private void notificationForUrgentDiagnosticOrder(DiagnosticOrder order) {
        if (order == null) {
            return;
        }

        if (!isUrgentDiagnosticOrder(order)) {
            LOG.debug("[DiagnosticOrderService] Urgent notification skipped. orderId={} reason=not_urgent", order.getId());
            return;
        }

        Long departmentId = order.getFromDepartmentId();
        DepartmentDTO department = departmentId != null
                ? departmentHelper.getDepartment(departmentId)
                : null;

        if (departmentId == null) {
            LOG.warn(
                    "[DiagnosticOrderService] Urgent notification skipped. orderId={} reason=missing_department",
                    order.getId()
            );
            return;
        }

        String login = SecurityUtils.getCurrentUserLogin().orElse(null);

        Patient patient = resolvePatient(order.getPatientId()).orElse(null);

        Map<String, List<NotificationResolvedRecipientDTO>> recipientsByRule =
                notificationHelper.resolveRecipients(
                        departmentId,
                        login,
                        order.getCreatedBy(),
                        patient,
                        null,
                        false
                );

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("order_id", order.getId());
        data.put("patient_id", order.getPatientId());
        data.put("patient_name", notificationHelper.getPatientName(patient));
        data.put("encounter_id", order.getEncounter() != null ? order.getEncounter().getId() : "");
        data.put("department_id", departmentId);
        data.put("department_name", department != null ? department.name() : "");
        data.put("status", order.getStatus() != null ? order.getStatus().toString() : "");
        data.put("submitted_by", order.getSubmittedBy() != null ? order.getSubmittedBy() : "");
        data.put("submitted_date", order.getSubmittedDate() != null ? order.getSubmittedDate().toString() : "");
        try {
            LOG.info(
                    "[DiagnosticOrderService] Calling Notification Service. orderId={} departmentId={} notificationCode={}",
                    order.getId(),
                    departmentId,
                    NotificationCode.URGENT_DIAGNOSTIC_ORDER_SUBMITTED
            );
            LOG.debug(
                    "[DiagnosticOrderService] Notification payload context. orderId={} departmentId={} recipientsByRule={} dataKeys={}",
                    order.getId(),
                    departmentId,
                    recipientsByRule,
                    data.keySet()
            );

            notificationHelper.sendNotification(
                    null,
                    NotificationCode.URGENT_DIAGNOSTIC_ORDER_SUBMITTED,
                    recipientsByRule,
                    data,
                    "DIAGNOSTIC_ORDER",
                    order.getId()
            );

            LOG.info("[DiagnosticOrderService] Notification Service completed successfully. orderId={} departmentId={} notificationCode={}",
                    order.getId(), departmentId, NotificationCode.URGENT_DIAGNOSTIC_ORDER_SUBMITTED);

        } catch (Exception e) {
            LOG.error(
                    "[DiagnosticOrderService] Notification Service failed. orderId={} departmentId={} notificationCode={} message={}",
                    order.getId(),
                    departmentId,
                    NotificationCode.URGENT_DIAGNOSTIC_ORDER_SUBMITTED,
                    e.getMessage(),
                    e
            );
        }
    }


    private boolean isUrgentDiagnosticOrder(DiagnosticOrder order) {
        return order != null && Boolean.TRUE.equals(order.getIsUrgent());
    }

    private Optional<Patient> resolvePatient(Long patientId) {
        if (patientId == null) {
            return Optional.empty();
        }

        return patientRepository.findById(patientId);
    }
}