package com.dazzle.asklepios.service;

import com.dazzle.asklepios.domain.DiagnosticOrder;
import com.dazzle.asklepios.domain.Patient;
import com.dazzle.asklepios.domain.enumeration.DiagnosticOrderTestStatus;
import com.dazzle.asklepios.domain.enumeration.DiagnosticStatus;
import com.dazzle.asklepios.repository.DiagnosticOrderRepository;
import com.dazzle.asklepios.repository.DiagnosticOrderTestRepository;
import com.dazzle.asklepios.repository.PatientRepository;
import com.dazzle.asklepios.service.dto.medicalsheets.diagnosticorders.DiagnosticOrderCreateDTO;
import com.dazzle.asklepios.service.dto.medicalsheets.diagnosticorders.DiagnosticOrderUpdateDTO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;

@Service
@Transactional
public class DiagnosticOrderService {

    private static final Logger LOG = LoggerFactory.getLogger(DiagnosticOrderService.class);

    private final DiagnosticOrderRepository diagnosticOrderRepository;
    private final DiagnosticOrderTestRepository diagnosticOrderTestRepository;
    private final PatientRepository patientRepository;

    public DiagnosticOrderService(
            DiagnosticOrderRepository diagnosticOrderRepository,
            DiagnosticOrderTestRepository diagnosticOrderTestRepository,
            PatientRepository patientRepository
    ) {
        this.diagnosticOrderRepository = diagnosticOrderRepository;
        this.diagnosticOrderTestRepository = diagnosticOrderTestRepository;
        this.patientRepository = patientRepository;
    }

    /**
     * Creates a new {@link DiagnosticOrder}.
     *
     * Defaults applied when fields are not provided:
     * - status defaults to {@link DiagnosticStatus#NEW}
     * - labStatus defaults to {@link DiagnosticStatus#NEW}
     * - radStatus defaults to {@link DiagnosticStatus#NEW}
     * - isUrgent defaults to {@code false}
     *
     * Notes:
     * - saveDraft is expected to be controlled by the caller (UI/controller).
     * - orderNumber is generated by the database (not set here).
     */
    public DiagnosticOrder create(DiagnosticOrderCreateDTO dto) {
        LOG.debug("[DiagnosticOrderService] CREATE - start. payload={}", dto);

        DiagnosticOrder order = new DiagnosticOrder();

        order.setEncounterId(dto.encounterId());
        order.setPatientId(dto.patientId());
        // Apply safe defaults to avoid null workflow statuses

        DiagnosticStatus labStatus = dto.labStatus() != null ? dto.labStatus() : DiagnosticStatus.NEW;
        DiagnosticStatus radStatus = dto.radStatus() != null ? dto.radStatus() : DiagnosticStatus.NEW;

        order.setStatus(DiagnosticStatus.NEW);
        order.setLabStatus(labStatus);
        order.setRadStatus(radStatus);
        order.setFromDepartmentId(dto.fromDepartmentId());
        order.setFromFacilityId(dto.fromFacilityId());

        order.setSaveDraft(true);
        order.setIsUrgent(dto.isUrgent() != null ? dto.isUrgent() : false);

        DiagnosticOrder saved = diagnosticOrderRepository.save(order);

        LOG.debug(
                "[DiagnosticOrderService] CREATE - done. id={} status={} saveDraft={} labStatus={} radStatus={} isUrgent={}",
                saved.getId(),
                saved.getStatus(),
                saved.getSaveDraft(),
                saved.getLabStatus(),
                saved.getRadStatus(),
                saved.getIsUrgent(),
                saved.getFromDepartmentId(),
                saved.getFromFacilityId()
        );

        return saved;
    }


    public DiagnosticOrder update(DiagnosticOrder existing, DiagnosticOrderUpdateDTO dto) {
        LOG.debug("[DiagnosticOrderService] UPDATE - start. id={} payload={}", existing.getId(), dto);


        existing.setEncounterId(dto.encounterId());

        if (dto.isUrgent() != null) {
            existing.setIsUrgent(dto.isUrgent());
        }

        DiagnosticOrder saved = diagnosticOrderRepository.save(existing);

        LOG.debug(
                "[DiagnosticOrderService] UPDATE - done. id={} status={} saveDraft={} isUrgent={}",
                saved.getId(),
                saved.getStatus(),
                saved.getSaveDraft(),
                saved.getIsUrgent(),
                saved.getFromDepartmentId(),
                saved.getFromFacilityId()
        );

        return saved;
    }

    /**
     * Retrieves diagnostic orders by encounter id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByEncounter(Long encounterId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER - encounterId={} pageable={}", encounterId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByEncounterId(encounterId, pageable);

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_ENCOUNTER - done. encounterId={} returned={} totalElements={} totalPages={}",
                encounterId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    public Page<DiagnosticOrder> findByEncounterAndStatus(Long encounterId, DiagnosticStatus status, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_ENCOUNTER_AND_STATUS - encounterId={} status={} pageable={}", encounterId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByEncounterIdAndStatus(encounterId, status, pageable);

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_ENCOUNTER_AND_STATUS - done. encounterId={} status={} returned={} totalElements={} totalPages={}",
                encounterId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    /**
     * Retrieves diagnostic orders by patient id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByPatient(Long patientId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT - patientId={} pageable={}", patientId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_Id(patientId, pageable);

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_PATIENT - done. patientId={} returned={} totalElements={} totalPages={}",
                patientId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    public Page<DiagnosticOrder> findByPatientAndStatus(Long patientId, DiagnosticStatus status, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_STATUS - patientId={} status={} pageable={}", patientId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndStatus(patientId, status, pageable);

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_PATIENT_AND_STATUS - done. patientId={} status={} returned={} totalElements={} totalPages={}",
                patientId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    /**
     * Retrieves diagnostic orders by patient id + encounter id with an optional status filter.
     */
    @Transactional(readOnly = true)
    public Page<DiagnosticOrder> findByPatientAndEncounter(Long patientId, Long encounterId, Pageable pageable) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER - patientId={} encounterId={} pageable={}",
                patientId, encounterId, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndEncounterId(patientId, encounterId, pageable);

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER - done. patientId={} encounterId={} returned={} totalElements={} totalPages={}",
                patientId, encounterId, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    public Page<DiagnosticOrder> findByPatientAndEncounterAndStatus(
            Long patientId,
            Long encounterId,
            DiagnosticStatus status,
            Pageable pageable
    ) {
        LOG.debug("[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER_AND_STATUS - patientId={} encounterId={} status={} pageable={}",
                patientId, encounterId, status, pageable);

        Page<DiagnosticOrder> page = diagnosticOrderRepository.findByPatient_IdAndEncounterIdAndStatus(
                patientId, encounterId, status, pageable
        );

        LOG.debug(
                "[DiagnosticOrderService] FIND_BY_PATIENT_AND_ENCOUNTER_AND_STATUS - done. patientId={} encounterId={} status={} returned={} totalElements={} totalPages={}",
                patientId, encounterId, status, page.getNumberOfElements(), page.getTotalElements(), page.getTotalPages()
        );

        return page;
    }

    /**
     * Submits a draft order.
     *
     * Side effects:
     * - Updates order: saveDraft=false, status=SUBMITTED, submittedBy/submittedDate set
     * - Updates tests: bulk updates all tests under this order to SUBMITTED, excluding CANCELLED tests
     *
     * IMPORTANT:
     * - Controller must validate draft state / authorization (per current decision).
     */
    public DiagnosticOrder submit(DiagnosticOrder existing, String submittedBy) {
        LOG.debug(
                "[DiagnosticOrderService] SUBMIT - start. orderId={} currentSaveDraft={} currentStatus={} submittedBy={}",
                existing.getId(),
                existing.getSaveDraft(),
                existing.getStatus(),
                submittedBy
        );

        existing.setSaveDraft(false);
        existing.setStatus(DiagnosticStatus.SUBMITTED);
        existing.setSubmittedBy(submittedBy);
        existing.setSubmittedDate(Instant.now());

        DiagnosticOrder saved = diagnosticOrderRepository.save(existing);

        int updatedTests = diagnosticOrderTestRepository.bulkUpdateStatusForOrder(
                saved.getId(),
                DiagnosticOrderTestStatus.SUBMITTED
        );

        LOG.debug(
                "[DiagnosticOrderService] SUBMIT - done. orderId={} newSaveDraft={} newStatus={} submittedDate={} updatedTests={}",
                saved.getId(),
                saved.getSaveDraft(),
                saved.getStatus(),
                saved.getSubmittedDate(),
                updatedTests
        );

        return saved;
    }

    /**
     * Deletes a diagnostic order by id.
     *
     * Note:
     * - This does not cascade delete tests unless configured at DB/entity level.
     * - Controller is responsible for guarding deletion business rules if any.
     */
    public void delete(Long id) {
        LOG.debug("[DiagnosticOrderService] DELETE - start. id={}", id);
        diagnosticOrderRepository.deleteById(id);
        LOG.debug("[DiagnosticOrderService] DELETE - done. id={}", id);
    }
}
